name: Generate sitemap
on:
  push:
    branches:
      - main
    paths:
      - '**/*.html'
jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://natashagarg.github.io/SidhiAssociate
          sitemap-format: xml
      - name: Commit sitemap if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "Update sitemap" || echo "No changes to commit"
          git push
